### ISSUE TITLE
Exclude the `externals` file type from the telescope extension results

### ISSUE THREAD

**Issue by nfielder** [xvzc/chezmoi.nvim#17]
Hi!

Thanks so much for your hard work on this plugin - it's great!

Would it be possible to modify the arguments provided to `chezmoi list` to exclude file types of `externals`? I have a few external archives (such as zsh-syntax-highlighting) that means the function returns many files I would never edit/manage.

<details><summary>Expand for context</summary>
<p>

For context I'm using the below key map:
```lua
vim.keymap.set('n', '<leader>sc', telescope.extensions.chezmoi.find_files, { desc = '[S]earch [C]hezmoi Managed Files' })
```

And my results look like so because of my externals:
![image](https://github.com/user-attachments/assets/772a6d03-2544-48dd-b360-eabfa695c071)

</p>
</details> 

Looking at the source code it seems the args are currently hardcoded: https://github.com/xvzc/chezmoi.nvim/blob/faf61465718424696269b2647077331b3e4605f1/lua/telescope/_extensions/find_files.lua#L16-L23

For more flexibility, perhaps the function can be modified to allow providing custom options that can override the default args?

**Comment by xvzc** [comment]
Hmm.. i don't think it is a good idea to make the function modifiable, but this is not a expected behavior for sure. maybe we should add `--exclude=externals` as a option for the list command. Would that be fine?

**Comment by nfielder** [comment]
That sounds good to me! I've validated the functionality in my [personal configuration](https://github.com/nfielder/dotfiles/blob/564602ffebcca498e54fd66b36deccd43cbcb746/home/private_dot_config/nvim/lua/custom/plugins/telescope.lua#L147) and it works as expected.

I've opened a PR for the change in #18.
