### ISSUE TITLE
Why does Telescope chezmoi find_files show files in ~ not ~/.local/share/chezmoi

### ISSUE THREAD

**Issue by patrick-motard** [xvzc/chezmoi.nvim#19]
Why does `Telescope chezmoi find_files` list files that have been applied to the system instead of the files in the chezmoi repo dir?

We want to be modifying files in the chezmoi repo dir, not the files applied to the system. Especially in the case of templates.

**Comment by xvzc** [comment]
It shows the path of files that has been applied to the system but once you open the file, it will open the orgin.

**Comment by xvzc** [comment]
you might wanna take a look at **Treat all files in chezmoi source directory as chezmoi files** in the readme. And use the telescope's builtin fuzzy finder with the cwd value of ~/.local/chezmoi. that would work as expected i think.
