### ISSUE TITLE
question about netrw

### ISSUE THREAD

**Issue by azinsharaf** [xvzc/chezmoi.nvim#3]
very interesting plugin! 
In addition of using this plugin to manage my chezmoi in neovim i am wondering if you have any solution for my question here:
https://github.com/twpayne/chezmoi/discussions/3511

**Comment by azinsharaf** [comment]
not really. i've switched to your plugin.

**Comment by xvzc** [comment]
Yeah but i'm asking if you mind me closing this issue.
