### ISSUE TITLE
using telescope

### ISSUE THREAD

**Issue by azinsharaf** [xvzc/chezmoi.nvim#4]
i've added the telescope integration part but running it still shows the original dotfiles not the chezmio dotfiles. What am i missing?

![image](https://github.com/xvzc/chezmoi.nvim/assets/10101468/81db4b15-1bfb-43c4-a395-55899fd87dcf)

**Comment by xvzc** [comment]
Yeah it's because i made it that way.. the list of files will be basically destination directories. if you press enter, then the neovim will automatically open the source files in the chezmoi directory

**Comment by azinsharaf** [comment]
got it, thanks!
